version: "3.8"

networks:
    network:

volumes:
    mysql:

services:

    customer-notes-ai-mysql:
        image: mysql:8.0
        container_name: customer-notes-ai-mysql
        platform: linux/amd64
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: $DB_DATABASE
            MYSQL_ROOT_PASSWORD: $DB_PASSWORD
        command: "--log-bin-trust-function-creators=1"
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - network
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE

    customer-notes-ai-web:
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./Dockerfile
        image: customer-notes-ai-web
        platform: linux/amd64
        container_name: customer-notes-ai-web
        tty: true
        working_dir: /var/www/app
        volumes:
            - ./src:/var/www/app
        depends_on:
            - customer-notes-ai-mysql
        ports:
            - 8080:80
        networks:
            - network
